//聊天界面主题样式

export const lightTheme = {
  overlay: 'rgba(0, 0, 0, 0)',
  background: '#fffafc',
  headerText: '#8f6575',
  messageBubbleUser: '#ffe4f1',
  messageBubbleAssistant: '#ffffff',
  messageText: '#b37b8e',
  messageTextAssistant: '#8f6575',
  inputBackground: '#fff',
  inputText: '#8f6575',
  inputBorder: '#e0e0e0',
  actionText: '#f39ab5',
  disabledText: '#ccc',
  markdownBody: '#8f6575',
  markdownCodeBlockBg: '#f0f0f0',
  markdownCodeBlockBorder: '#ccc',
  borderColor: '#fde2e4',
  headerTitle: '#f39ab5',
  settingsButton: '#82a9e8',
  sendButton: '#ff8fab',
  sendButtonText: '#fff',
  switcherText: '#ff8fab',
  footerActionText: '#ff8fab',
  inputContainerBackground: 'rgba(255, 250, 252, 0.8)',
  placeholderText: '#b37b8e',
  editModeButtonBg: '#fde2e4',
  editModeButtonText: '#b37b8e',
  editModeButtonBgActive: '#ff8fab',
  editModeButtonTextActive: '#fff',
};

export const darkTheme = {
  overlay: 'rgba(0, 0, 0, 0.9)',
  background: '#0d0d0d',
  headerText: '#f5d7e3',
  messageBubbleUser: '#1a1a1a',
  messageBubbleAssistant: '#202020',
  messageText: '#eab7c8',
  messageTextAssistant: '#f5d7e3',
  inputBackground: '#1f1f1f',
  inputText: '#f5d7e3',
  inputBorder: '#4a273a',
  actionText: '#f39ab5',
  disabledText: '#555',
  markdownBody: '#f5d7e3',
  markdownCodeBlockBg: '#262626',
  markdownCodeBlockBorder: '#4a273a',
  borderColor: '#4a273a',
  headerTitle: '#f39ab5',
  settingsButton: '#f39ab5',
  sendButton: '#f39ab5',
  sendButtonText: '#0d0d0d',
  switcherText: '#f39ab5',
  footerActionText: '#f39ab5',
  inputContainerBackground: 'rgba(13, 13, 13, 0.8)',
  placeholderText: 'rgba(254, 181, 210, 0.8)',
  editModeButtonBg: '#4a273a',
  editModeButtonText: '#f5d7e3',
  editModeButtonBgActive: '#f39ab5',
  editModeButtonTextActive: '#0d0d0d',
};
